[tool.poetry]
name = "aoc"
version = "0.1.0"
description = ""
authors = ["MAXIMILIAN ZWIESLER <maximilian.zwiesler@mercedes-benz.com>"]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
